from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        """
        General set up function for the GUI.
        """
        # first set up window
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.mainPage = QtWidgets.QWidget(MainWindow)
        self.mainPage.setObjectName("mainPage")
        self.designWindow = QtWidgets.QWidget(self.mainPage)
        self.designWindow.setGeometry(QtCore.QRect(70, 30, 441, 201))
        self.designWindow.setObjectName("designWindow")
        self.simWindow = QtWidgets.QWidget(self.mainPage)
        self.simWindow.setGeometry(QtCore.QRect(70, 270, 441, 201))
        self.simWindow.setObjectName("simWindow")
        self.launch_button = QtWidgets.QPushButton(self.mainPage)
        self.launch_button.setGeometry(QtCore.QRect(650, 490, 111, 51))
        self.launch_button.setObjectName("launch_button")
        self.af_d_list = QtWidgets.QListWidget(self.mainPage)
        self.af_d_list.setGeometry(QtCore.QRect(630, 60, 141, 81))
        self.af_d_list.setObjectName("af_d_list")
        item = QtWidgets.QListWidgetItem()
        self.af_d_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.af_d_list.addItem(item)
        self.fc_list = QtWidgets.QListWidget(self.mainPage)
        self.fc_list.setGeometry(QtCore.QRect(630, 200, 141, 41))
        self.fc_list.setObjectName("fc_list")
        item = QtWidgets.QListWidgetItem()
        self.fc_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.fc_list.addItem(item)
        # button and labels
        self.wind_box = QtWidgets.QDoubleSpinBox(self.mainPage)
        self.wind_box.setGeometry(QtCore.QRect(710, 350, 62, 22))
        self.wind_box.setObjectName("wind_box")
        self.wind_name = QtWidgets.QLineEdit(self.mainPage)
        self.wind_name.setGeometry(QtCore.QRect(632, 350, 61, 20))
        self.wind_name.setObjectName("wind_name")
        self.alt_name = QtWidgets.QLineEdit(self.mainPage)
        self.alt_name.setGeometry(QtCore.QRect(630, 380, 61, 20))
        self.alt_name.setObjectName("alt_name")
        self.alt_box = QtWidgets.QDoubleSpinBox(self.mainPage)
        self.alt_box.setGeometry(QtCore.QRect(710, 380, 62, 22))
        self.alt_box.setObjectName("alt_box")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.mainPage)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 10, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.mainPage)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 240, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.fc_nam = QtWidgets.QLineEdit(self.mainPage)
        self.fc_nam.setGeometry(QtCore.QRect(630, 170, 113, 20))
        self.fc_nam.setObjectName("fc_nam")
        self.af_d_name = QtWidgets.QLineEdit(self.mainPage)
        self.af_d_name.setGeometry(QtCore.QRect(630, 30, 113, 20))
        self.af_d_name.setObjectName("af_d_name")
        self.lc_name = QtWidgets.QLineEdit(self.mainPage)
        self.lc_name.setGeometry(QtCore.QRect(630, 320, 113, 20))
        self.lc_name.setObjectName("lc_name")
        MainWindow.setCentralWidget(self.mainPage)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        # making tabs
        self.menubar.setObjectName("menubar")
        self.menumainPage = QtWidgets.QMenu(self.menubar)
        self.menumainPage.setObjectName("menumainPage")
        self.menuExtra_Customization = QtWidgets.QMenu(self.menubar)
        self.menuExtra_Customization.setObjectName("menuExtra_Customization")
        self.menuEquations_and_Explainations = QtWidgets.QMenu(self.menubar)
        self.menuEquations_and_Explainations.setObjectName("menuEquations_and_Explainations")
        MainWindow.setMenuBar(self.menubar)
        # status bar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menumainPage.menuAction())
        self.menubar.addAction(self.menuExtra_Customization.menuAction())
        self.menubar.addAction(self.menuEquations_and_Explainations.menuAction())
        # putting everything into the main window
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """
        Superficial GUI labels and texts
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.launch_button.setText(_translate("MainWindow", "Launch!"))
        __sortingEnabled = self.af_d_list.isSortingEnabled()
        self.af_d_list.setSortingEnabled(False)
        item = self.af_d_list.item(0)
        item.setText(_translate("MainWindow", "8\" Diameter"))
        item = self.af_d_list.item(1)
        item.setText(_translate("MainWindow", "5\"  Diameter"))
        self.af_d_list.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.fc_list.isSortingEnabled()
        self.fc_list.setSortingEnabled(False)
        item = self.fc_list.item(0)
        item.setText(_translate("MainWindow", "Tri-form"))
        item = self.fc_list.item(1)
        item.setText(_translate("MainWindow", "Cruci-form"))
        self.fc_list.setSortingEnabled(__sortingEnabled)
        self.wind_name.setText(_translate("MainWindow", "Wind"))
        self.alt_name.setText(_translate("MainWindow", "Altitude"))
        self.lineEdit_3.setText(_translate("MainWindow", "Design Window"))
        self.lineEdit_4.setText(_translate("MainWindow", "Launch Window"))
        self.fc_nam.setText(_translate("MainWindow", "Fin Customizations"))
        self.af_d_name.setText(_translate("MainWindow", "Air Frame Diameter"))
        self.lc_name.setText(_translate("MainWindow", "Launch Conditions"))
        self.menumainPage.setTitle(_translate("MainWindow", "Home"))
        self.menuExtra_Customization.setTitle(_translate("MainWindow", "Extra Customization"))
        self.menuEquations_and_Explainations.setTitle(_translate("MainWindow", "Equations and Explainations"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
